name: medexpert
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - simpledorff==0.0.2
    - tqdm==4.67.1
    - backoff==2.2.1
    - faiss-cpu==1.9.0
    - huggingface-hub==0.34.3
    - jsonlines==4.0.0
    - numpy>=1.15.0,<1.27.0
    - openai==1.93.0
    - spacy==3.7.4
    - "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl"
    - python-dotenv==1.2.1
    - regex==2025.11.3
    - sentence-transformers==5.1.2
    - pandas==2.3.3
    - datasets==4.4.1
    - registrable
    - nest_asyncio
